# TCL File Generated by Component Editor 11.1
# Sat Jan 27 09:43:52 CET 2018
# DO NOT MODIFY


# +-----------------------------------
# | 
# | 1 "1" v1.0
# | null 2018.01.27.09:43:52
# | 
# | 
# | C:/Users/this-pc/Desktop/Projects_VHDL/Qsys_Nios/1.spi_master.vhd
# | 
# |    ./1.spi_master.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module 1
# | 
set_module_property NAME 1
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME 1
set_module_property TOP_LEVEL_HDL_FILE 1.spi_master.vhd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file 1.spi_master.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 12800

set_interface_property clock_sink ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sclk
# | 
add_interface sclk clock end
set_interface_property sclk clockRate 0

set_interface_property sclk ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_receiver
# | 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint ""
set_interface_property interrupt_receiver associatedClock clock_sink
set_interface_property interrupt_receiver associatedReset reset_sink
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS

set_interface_property interrupt_receiver ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_master
# | 
add_interface nios_custom_instruction_master nios_custom_instruction start
set_interface_property nios_custom_instruction_master clockCycle 0

set_interface_property nios_custom_instruction_master ENABLED true
# | 
# +-----------------------------------
